<a href="https://colab.research.google.com/github/dark-d07/DIGITAL-COUNTDOWN/blob/master/Copy_of_ASSIGNMENT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.zeros((5,3))
b=a.astype('int')
print("Initially all bowling figures as zero:\n",b)

Initially all bowling figures as zero:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
c=np.array([
    [10,3,6],
    [9,4,3],
    [8,0,10],
    [7,1,30],
    [4,8,40]
])
print("Filled with Bowling figure with Max 10 overs per bowler:\n",c)

Filled with Bowling figure with Max 10 overs per bowler:
 [[10  3  6]
 [ 9  4  3]
 [ 8  0 10]
 [ 7  1 30]
 [ 4  8 40]]


In [ ]:
d=c[:3,:]
print("Fast Bowling(Considering first 3 bowlers are first bowlers):\n",d)

Fast Bowling(Considering first 3 bowlers are first bowlers):
 [[10  3  6]
 [ 9  4  3]
 [ 8  0 10]]


In [ ]:
e=c[:,2]/c[:,0]
print("Bowling of All Bowlers:\n",e)

Bowling of All Bowlers:
 [ 0.6         0.33333333  1.25        4.28571429 10.        ]


In [ ]:
runs=np.array([10,20,56,7,100,94,39,64,99,87,54])

In [ ]:
minrun=np.min(runs)
maxrun=np.max(runs)
print("Runs Scored By Batman:",runs)
print("Minimum Runs:",minrun)
print("Maximum Run:",maxrun)

Runs Scored By Batman: [ 10  20  56   7 100  94  39  64  99  87  54]
Minimum Runs: 7
Maximum Run: 100


In [ ]:
trun=np.sum(runs)
print("Total Run Scores:",trun)

Total Run Scores: 630


In [ ]:
rrun=trun/50
print("Run Rate:",rrun)

Run Rate: 12.6


In [ ]:
drun=runs[runs>9]
drun=len(drun)
print("Batmans Scored Double digit:",drun)

Batmans Scored Double digit: 10


In [ ]:
srun=np.sort(runs)
print("The sorted scores:\n",srun)

The sorted scores:
 [  7  10  20  39  54  56  64  87  94  99 100]


In [ ]:
aruns=runs+5
print("Scores after Bonus +5:\n",aruns)

Scores after Bonus +5:
 [ 15  25  61  12 105  99  44  69 104  92  59]


In [ ]:
torun=runs[:5]
tairun=runs[5:]
print("Top-Order's Scores:",torun)
print("Tail-Ender's Scores:",tairun)

Top-Order's Scores: [ 10  20  56   7 100]
Tail-Ender's Scores: [94 39 64 99 87 54]


In [ ]:
runs1=np.insert(runs,len(runs),30)
print("12th Batman is included:\n", runs1)

12th Batman is included:
 [ 10  20  56   7 100  94  39  64  99  87  54  30]


In [ ]:
jrun=np.random.randint(1,100,size=11)
print("Random Jersey Number:\n",jrun)

Random Jersey Number:
 [67 86 12 10  2 46 75 42 62 49 34]


In [ ]:
a1=np.array([10,20,30,40,50,60,70,80,90,100,110])
a2=np.array([1,11,22,33,44,55,66,77,88,99,111])
a3=np.array([2,4,6,8,10,11,23,45,67,89,78])

In [ ]:
k=a1+a2+a3
print("The Total Score by individual bats man in tournament:\n",k)

The Total Score by individual bats man in tournament:
 [ 13  35  58  81 104 126 159 202 245 288 299]


In [ ]:
print("The Average Score by individual bats man in tournament:\n",k/3)

The Average Score by individual bats man in tournament:
 [ 4.33333333 11.66666667 19.33333333 27.         34.66666667 42.
 53.         67.33333333 81.66666667 96.         99.66666667]


In [ ]:
max=np.max(k)
print("The Highest Run Getter is",np.argmax(k)+1,"with score:",max)

The Highest Run Getter is 11 with score: 299
